# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [60]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import os
import ipywidgets as widgets
import geopy

# Import API key
import mapkey
 
# Configure gmaps
import gmaps
gmaps.configure(api_key='mapkey')

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [62]:
output_df = pd.read_csv('output_data.csv')

vacation_df = output_df.drop(columns=["Unnamed: 0"])
vacation_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Pascagoula,1,US,1586643542,60,30.37,-88.56,73.99,10.29
1,Wuwei,28,CN,1586643543,25,37.93,102.64,39.99,1.63
2,Bosaso,13,SO,1586643544,68,11.28,49.18,82.92,4.74
3,Puerto Ayora,40,EC,1586643404,70,-0.74,-90.35,84.20,6.93
4,Hobart,75,AU,1586643370,57,-42.88,147.33,53.01,13.87
...,...,...,...,...,...,...,...,...,...
561,Hailey,5,US,1586644206,32,43.52,-114.32,55.40,24.16
562,Goderich,1,CA,1586644148,54,43.75,-81.72,53.01,8.99
563,Uvira,68,CD,1586644208,50,-3.41,29.15,72.99,2.53
564,Lae,98,PG,1586644209,58,-6.72,146.98,87.04,2.82
565,Rock Sound,85,BS,1586644197,86,24.90,-76.20,75.29,17.74

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [68]:

vacation_df = pd.DataFrame(vacation_df, columns = ["City","Lat","Lng","Max Temp", "Wind Speed", "Humidity","Cloudiness"])

temp = (vacation_df["Max Temp"] <= 90) & (new_types_df["Max Temp"] > 75)
wind = vacation_df["Wind Speed"] < 10
humidity = vacation_df["Humidity"] < 10
cloudiness = vacation_df["Cloudiness"] == 0

# new_types_df[max_temp & wind_speed & cloudiness]
idealvacation_df[temp & wind & humidity & cloudiness]

Empty DataFrame
Columns: [City, Max Temp, Wind Speed, Humidity, Cloudiness]
Index: []

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.